language: php

php:
  - 7.1

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_script:
  - cp .env.travis .env
  - mysql -e 'create database employee_portal_test;'
  - mysql -e 'create database emp_portal_master_test;'
  - mysql -e 'create database emp_org_tenant_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate
  - php artisan migrate:all --database=master_test
  - php artisan db:seed --class=TestSeeder --database=master_test

script:
  - php artisan key:generate
  - composer dump-autoload
  - npm install
  - npm run production
  - vendor/bin/phpunit
